In [36]:
import pandas as pd

Вывести содержимое таблицы country_language

In [37]:
df = pd.read_sql(
"""
SELECT
  *
FROM
  country_language
""",
"postgresql://netology:NetoSQL2019@84.201.153.170:19001/world-db"
)

In [38]:
df.head()

  country_code    language  is_official  percentage
0          AFG      Pashto         True        52.4
1          NLD       Dutch         True        95.6
2          ANT  Papiamento         True        86.2
3          ALB   Albaniana         True        97.9
4          DZA      Arabic         True        86.0

Вывести список основных языков, по каждой стране. Для этого:
* Соедините таблицы country и country_language, при помощи оператора присоединения join;
* Оставьте только те строчки, в которых значение колонки “is_official” имеет значение «True». Выполняем это при помощи оператора where.

In [39]:
df = pd.read_sql(
"""
SELECT
  name, language
FROM
  country c
INNER JOIN
  country_language cl
ON
  c.code = cl.country_code
WHERE
  is_official = True
""",
"postgresql://netology:NetoSQL2019@84.201.153.170:19001/world-db"
)
df.head()

                   name    language
0           Afghanistan      Pashto
1           Netherlands       Dutch
2  Netherlands Antilles  Papiamento
3               Albania   Albaniana
4               Algeria      Arabic

"Вывести список основных языков, у каждой страны”, теперь уже средствами pandas

In [40]:
df_country = pd.read_sql(
"""
SELECT
  *
FROM
  country
""",
"postgresql://netology:NetoSQL2019@84.201.153.170:19001/world-db"
)
df_country.head()

,code,name,continent,region,surface_area,indep_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
0,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
1,NLD,Netherlands,Europe,Western Europe,41526.0,1581.0,15864000,78.3,371362.0,360478.0,Nederland,Constitutional Monarchy,Beatrix,5.0,NL
2,ANT,Netherlands Antilles,North America,Caribbean,800.0,NaN,217000,74.7,1941.0,NaN,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Beatrix,33.0,AN
3,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
4,DZA,Algeria,Africa,Northern Africa,2381740.0,1962.0,31471000,69.7,49982.0,46966.0,Al-Jazair/Algérie,Republic,Abdelaziz Bouteflika,35.0,DZ

In [41]:
df_country_language = pd.read_sql(
"""
SELECT
  *
FROM
  country_language
""",
"postgresql://netology:NetoSQL2019@84.201.153.170:19001/world-db"
)
df_country_language.head()

  country_code    language  is_official  percentage
0          AFG      Pashto         True        52.4
1          NLD       Dutch         True        95.6
2          ANT  Papiamento         True        86.2
3          ALB   Albaniana         True        97.9
4          DZA      Arabic         True        86.0

In [42]:
df_merged = df_country.merge(df_country_language, left_on='code', right_on='country_code', how='inner')
df_merged.head()

,code,name,continent,region,surface_area,indep_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2,country_code,language,is_official,percentage
0,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF,AFG,Pashto,True,52.4
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF,AFG,Dari,True,32.1
2,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF,AFG,Uzbek,False,8.8
3,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF,AFG,Turkmenian,False,1.9
4,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF,AFG,Balochi,False,0.9

In [43]:
df_merged[['name', 'language', 'is_official', ]]

                                     name    language  is_official
0                             Afghanistan      Pashto         True
1                             Afghanistan        Dari         True
2                             Afghanistan       Uzbek        False
3                             Afghanistan  Turkmenian        False
4                             Afghanistan     Balochi        False
..                                    ...         ...          ...
979                              Zimbabwe     English         True
980                              Zimbabwe      Nyanja        False
981                             Palestine      Arabic        False
982                             Palestine      Hebrew        False
983  United States Minor Outlying Islands     English         True

[984 rows x 3 columns]

In [46]:
filter_df_merged = df_merged['is_official'] == True
df_merged[['name', 'language', 'is_official']].loc[filter_df_merged]

                                     name    language  is_official
0                             Afghanistan      Pashto         True
1                             Afghanistan        Dari         True
5                             Netherlands       Dutch         True
9                    Netherlands Antilles  Papiamento         True
11                   Netherlands Antilles       Dutch         True
..                                    ...         ...          ...
957                               Estonia    Estonian         True
962                         United States     English         True
974                  Virgin Islands, U.S.     English         True
979                              Zimbabwe     English         True
983  United States Minor Outlying Islands     English         True

[238 rows x 3 columns]