In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('DAU-33, Вертелецкая, ДЗ №6, Python как инструмент анализа данных (Ответы) - Ответы на форму (1).csv', sep=',')

In [4]:
df.head()

,Отметка времени,Месяц,Название операции,Сумма,Категория,Регулярная трата
0,5/10/2022 21:03:28,1,Массаж,3500.0,Забота о себе,ЛОЖЬ
1,5/7/2022 21:13:01,1,Трамвай,25.0,Транспорт,ИСТИНА
2,5/7/2022 21:13:42,2,Стрижка,1000.0,Забота о себе,ИСТИНА
3,5/10/2022 21:03:56,2,Мобильная связь,400.0,Платежи и комиссии,ИСТИНА
4,5/10/2022 21:05:30,2,Молоко,70.0,Продукты питания,ЛОЖЬ

In [16]:
#создала новую переменную, включающую столбцы 'Сумма','Категория', т.к. в противном случае выводится общая статистика и для столбца с номером месяца, что некорректно.
df_amount_transaction = df[['Сумма','Категория']]

Общая статистика трат без учёта категорий

In [17]:
df_amount_transaction.describe()

             Сумма
count    21.000000
mean   1065.476190
std    1551.180119
min      25.000000
25%      70.000000
50%     350.000000
75%    1300.000000
max    5000.000000

Суммарные траты по категориям

In [18]:
df_amount_transaction.groupby(['Категория']).sum()

                      Сумма
Категория
Забота о себе       11400.0
Платежи и комиссии   8540.0
Продукты питания     1960.0
Транспорт             475.0